import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";

const sourcePath = new URL("../legal/participation-waiver-2026.2.json", import.meta.url);
const modulePath = new URL("../src/generated/participation-waiver.ts", import.meta.url);
const pagePath = new URL("../waiver.html", import.meta.url);
const privacyPath = new URL("../privacy.html", import.meta.url);
const privacyModulePath = new URL("../src/generated/privacy-media.ts", import.meta.url);
const sourceText = await readFile(sourcePath, "utf8");
const source = JSON.parse(sourceText);
const canonical = `${JSON.stringify(source)}\n`;
const hash = createHash("sha256").update(canonical).digest("hex");
const escape = (value) => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&#39;");

const generatedModule = `// Generated by scripts/generate-waiver.mjs. Do not edit.\n` +
  `export const generatedParticipationWaiver = Object.freeze(${JSON.stringify({ ...source, hash }, null, 2)} as const);\n`;

const privacyHtml = await readFile(privacyPath, "utf8");
const privacyMain = privacyHtml.match(/<main id="main" tabindex="-1">[\s\S]*?<\/main>/);
if (!privacyMain) throw new Error("privacy.html is missing its canonical legal main content");
const canonicalPrivacy = `${privacyMain[0].replaceAll("\r\n", "\n").trim()}\n`;
const privacyHash = createHash("sha256").update(canonicalPrivacy).digest("hex");
const privacyModule = `// Generated by scripts/generate-waiver.mjs. Do not edit.\n` +
  `export const generatedPrivacyMediaDocument = Object.freeze({ type: "privacy_media" as const, version: "2026.3", hash: "${privacyHash}" });\n`;

const renderBlock = (block) => block.kind === "list"
  ? `<ul>${block.items.map((item) => `<li>${escape(item)}</li>`).join("")}</ul>`
  : `<p>${escape(block.text)}</p>`;
const body = source.sections.map((section) =>
  `<section class="policy-section" id="${escape(section.slug)}"><h2>${section.number}. ${escape(section.title)}</h2>${section.blocks.map(renderBlock).join("")}</section>`
).join("");
const generatedPage = `<!doctype html>
<html lang="en-CA">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escape(source.title)} | Tim Lost Something?</title>
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="icon" href="/assets/favicon-32x32.png" type="image/png" sizes="32x32">
  <link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
  <link rel="manifest" href="/site.webmanifest">
  <meta name="description" content="Read the current Tim Lost Something? participation acknowledgement, waiver and release." />
  <meta name="robots" content="index,follow" />
  <link rel="canonical" href="https://www.timlostsomething.com/waiver" />
  <meta property="og:site_name" content="Tim Lost Something?" />
  <meta property="og:title" content="${escape(source.title)}" />
  <meta property="og:description" content="Read the current participation acknowledgement, waiver and release for the Seba Beach treasure hunt." />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="https://www.timlostsomething.com/waiver" />
  <meta property="og:image" content="https://www.timlostsomething.com/assets/photos/evidence-cash.jpg" />
  <meta name="twitter:card" content="summary_large_image" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400&amp;family=IBM+Plex+Mono:wght@400;500;600&amp;family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&amp;display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/css/style.css" />
  <link rel="stylesheet" href="/css/hunter.css" />
  <link rel="stylesheet" href="/css/campaign-shell.css" />
</head>
<body class="campaign-page campaign-page--document hunter-page waiver-page" data-campaign-route="waiver">
  <!-- CAMPAIGN_SHELL {"route":"waiver","skipLabel":"Skip to the participation waiver","skipTarget":"main"} -->
  <main id="main" tabindex="-1">
    <section class="hunter-hero" aria-labelledby="waiver-title"><div class="hunter-hero__inner"><p class="hunter-kicker">Participation legal document</p><h1 id="waiver-title">${escape(source.title)}</h1><p class="hunter-hero__lead">Version ${escape(source.version)} &middot; Effective ${escape(source.effectiveDateLabel)}</p></div></section>
    <article class="hunter-main legal-page"><p>${escape(source.intro)}</p>${body}<div class="action-row waiver-print-action"><button class="hunter-button" type="button" data-print-waiver>Print this waiver</button><a class="hunter-button hunter-button--quiet" href="/dashboard#waiver">Return to registration</a></div></article>
  </main>
  <!-- CAMPAIGN_FOOTER -->
  <script src="/js/site.js"></script>
  <script type="module" src="/assets/app/status.js"></script>
  <script type="module" src="/assets/app/waiver.js"></script>
</body>
</html>
`;

const check = process.argv.includes("--check");
if (!check) await mkdir(new URL("../src/generated/", import.meta.url), { recursive: true });
for (const [path, expected] of [[modulePath, generatedModule], [pagePath, generatedPage], [privacyModulePath, privacyModule]]) {
  if (check) {
    const actual = await readFile(path, "utf8").catch(() => "");
    if (actual !== expected) throw new Error(`${path.pathname} is stale; run npm run legal:generate`);
  } else {
    await writeFile(path, expected, "utf8");
  }
}
